openapi: 3.0.0
info:
  title: Cart Service API
  description: API documentation for the Cart Service
  version: 1.0.0
paths:
  /cart/add:
    post:
      summary: Add an item to the cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItem'
      responses:
        '200':
          description: Item added successfully
  /cart/items:
    get:
      summary: Get all items in the cart
      responses:
        '200':
          description: Fetched all items successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItem'
components:
  schemas:
    CartItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        quantity:
          type: integer
